apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore
  namespace: ronesans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetcore
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dotnetcore
    spec:
      containers:
      - name: dotnetcore
        image: public.ecr.aws/u3h5m1q5/ronesans_publicecr:21470
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 125M
            cpu: 100m
          limits:
            memory: 500M
            cpu: 300m

