apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-svc
spec:
  type: NodePort
  selector:
    app: dotnetcore
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30123
      protocol: TCP