apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-svc
  namespace: ronesans
spec:
  type: NodePort
  selector:
    app: dotnetcore
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30123
      protocol: TCP