# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: DevOpsLinuxPipeline

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  displayName: Terraform Init
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/ecr'
    backendServiceAWS: 'AWS-Ronesans'
    backendAWSBucketName: 'ronesans-poc'
    backendAWSKey: 'ronesans-poc/ronesans-poc.tfstate'

- task: TerraformTaskV2@2
  displayName: Terraform Plan
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/ecr'
    environmentServiceNameAWS: 'AWS-Ronesans'
  enabled: false

- task: TerraformTaskV2@2
  displayName: Terraform Apply
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/ecr'
    environmentServiceNameAWS: 'AWS-Ronesans'